### ISSUE TITLE
SUGGESTION: Also include musical notes on piano image?

### ISSUE THREAD

**Issue by Liquidream** [Neko250/pico8-api#6]
I often find that I know the notes that I want to enter into PICO-8 (e.g. **E**, **C#**, **A**, etc.), but have NO IDEA which keys map to which note.
So, was thinking it might be helpful if your (already v.useful) piano image also included the musical notes (for those of us that aren't piano players!)
I realise this may be a bit tricky as there are different octaves, but either way - wondered if you though this would be as useful as I would?
Thanks! :smiley:

**Comment by wh0am1-dev** [comment]
Done ! 😀
